[project]
name = "piotr-gorczyca-status-talk"
version = "0.1.0"
description = "Manim slides for status talk"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["slides*"]
